name: Release

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all packages
        run: pnpm build:packages

      - name: Build all applications
        run: pnpm build:apps

      - name: Generate changelog
        id: changelog
        run: |
          # Generate changelog from git commits
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --pretty=format:"- %s (%h)" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: SISO-PUBLIC ${{ github.ref }}
          body: |
            ## Changes in this Release
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ## Deployment
            - **Client Portal**: https://siso.agency/clients
            - **Partner Portal**: https://siso.agency/partners
            
            ## Bundle Analysis
            This release includes optimized bundles with:
            - 30-40% smaller bundle sizes
            - Improved code splitting
            - Enhanced caching strategies
            
            ## Breaking Changes
            Please check the migration guide if upgrading from a previous version.
          draft: false
          prerelease: false

      - name: Deploy to production
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./
          scope: ${{ secrets.VERCEL_ORG_ID }}

      - name: Update siso.agency routing
        run: |
          echo "Updating production routing for release ${{ github.ref }}..."
          curl -X POST "${{ secrets.DOMAIN_WEBHOOK_URL }}" \
            -H "Authorization: Bearer ${{ secrets.DOMAIN_WEBHOOK_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "action": "release_deploy", 
              "version": "${{ github.ref }}", 
              "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
            }'

      - name: Notify team
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: |
            🚀 SISO-PUBLIC ${{ github.ref }} has been released!
            
            ✅ Client Portal: https://siso.agency/clients
            ✅ Partner Portal: https://siso.agency/partners
            
            View release: ${{ github.event.release.html_url }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}